spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PROJECT_BOARD
    username: root
    password: 1

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect #Using the right database platform is extremly important on Spring Boot 2.0
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect #CONFLICTS WITH HEROKU from local host